# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 270bba675822b82bb1978498a574a52652768fa67912770fce2f32c22778ee3d403103a172e73ab037e56fa8a6c0c3b2f33d0311c6d96d4bfe53dd2cbc711848

test:
  secret_key_base: 7ddc5e53edb22e79d7864c26a426a542f69126ec563548775e211b6910339e293b71a4596066d5fd5d2c0a0d6c7180593c04f5916c5991790266f712c39afa8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
